version: '8.3'
services:
  dev-db:
    image: mysql
    ports:
      - 3307:3307
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: pooya
      MYSQL_PASSWORD: 05121
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 05121
    
